"""added user hashed_password

Revision ID: 8f3ddf674b19
Revises: 8f0f843b7a0f
Create Date: 2022-07-13 16:38:11.886915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f3ddf674b19'
down_revision = '8f0f843b7a0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
