"""add chats m2m

Revision ID: 9332f0da5674
Revises: bec2880e1f58
Create Date: 2022-07-13 14:47:27.939452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9332f0da5674'
down_revision = 'bec2880e1f58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chats_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('chat', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat'], ['chats.id'], name='fk_chats_users_chats_chat_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_chats_users_users_user_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chats_users')
    op.drop_table('chats')
    # ### end Alembic commands ###
