"""added message text field

Revision ID: cb691fb1d7a1
Revises: 10fc9d16b0d8
Create Date: 2022-07-15 14:29:06.999947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb691fb1d7a1'
down_revision = '10fc9d16b0d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('text', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'text')
    # ### end Alembic commands ###
