"""added user to messages table

Revision ID: efe9c1203ad1
Revises: cb691fb1d7a1
Create Date: 2022-07-20 11:32:03.362972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe9c1203ad1'
down_revision = 'cb691fb1d7a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_messages_users_id_user', 'messages', 'users', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_messages_users_id_user', 'messages', type_='foreignkey')
    op.drop_column('messages', 'user')
    # ### end Alembic commands ###
